const theme = {
  fontColorBlack: '#000',
  fontColorDarkblue: '#00256c',
  fontColorLightblue: '#0364de',
  backgroundColorLightgray: '#f3f4f8',
  backgroundColorDarkgray: '#767676',
  backgroundColorRed: '#dd001b',
  backgroundColorSkyblue: '#f5faff',
  backgroundColorBlue: '#283675',
  backgroundColorDarkblue: '#00256c',
  backgroundColorLightblue: '#0364de',
  borderColorDarkgray: '#aaa7a7',
  borderColorGray: '#d9dbe1',
  borderColorSkyblue: '#c7f3ff',
  borderColorDarkblue: '#00256c',
  btnLarge: '30px',
  large: '28px',
  btnRegular: '26px',
  regular: '24px',
  btnMedium: '22px',
  medium: '20px',
  btnSmall: '18px',
  small: '16px',
  borderColorSkyBlue: 'c7f3ff',
};

export default theme;
